### ISSUE TITLE
Enemy randomizer issues I found

### ISSUE THREAD

**Issue by InQuognito** [silent-destroyer/tunic-randomizer#14]
- The green spinner guys from the atoll usually spawn respecting the original entities rotation, which often times has them rolling off an edge uselessly since they travel forward a bit before turning
- The table passive entities could probably be removed from the rotation, but that’s more of a suggestion than anything.

**Comment by silent-destroyer** [comment]
The slorms behavior has already been fixed in the archipelago version and will be fixed in the next release of the standalone mod. Several other enemy rando issues have already been fixed over there as well and will be in the next release here as well, such as the crabs not being able to move and the gauntlet enemy spawns not working properly. 

As for the tables, I like them too much to remove them :P
